### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by kbs170** [openlayers/workshop#48]
Hi Tim,

I try to check out the "Openlayer Workshop". I'm on the point to start the workshop server with "npm install" and "npm start" ("In the resulting openlayers-workshop directory, run the following to get the workshop dependencies:....") Before that I have been installed node.js - is that right? But "npm" is unknown on my windows-7 machine. Please Is there a install-guide with a bit more introductions?

best
kbs170

**Comment by tsauerwein** [comment]
npm is installed with node.js. but it looks like npm is not available on your `PATH`. Can you try to add it manually?
http://stackoverflow.com/a/27864253/119937

**Comment by kbs170** [comment]
Yes, that helps, Thank you.

**Comment by kbs170** [comment]
Hi Tim,

the first example /basics/map.html includes a file named loader.js (<script src="/loader.js" type="text/javascript"></script>) But I can't find it. It's not in that folder.

Anyway... After I started the script http://localhost:4000/map.html the server crashed with

```
info serve-lib Parsing dependencies.
info serve-lib Debug server running http://localhost:4000/loader.js (Ctrl+C to stop)
C:\Temp\openlayers-workshop\node_modules\openlayers\node_modules\closure-util\lib\manager.js:172
      throw new Error('Could not find base.js');
      ^

Error: Could not find base.js
    at Manager.getDependencies (C:\Temp\openlayers-workshop\node_modules\openlayers\node_modules\closure-util\lib\manager.js:172:13)
    at Server._requestListener (C:\Temp\openlayers-workshop\node_modules\openlayers\node_modules\closure-util\lib\server.js:154:32)
    at Server.<anonymous> (C:\Temp\openlayers-workshop\node_modules\engine.io\lib\server.js:434:22)
    at Server.<anonymous> (C:\Temp\openlayers-workshop\node_modules\openlayers\node_modules\closure-util\node_modules\socket.io\lib\index.js:258:16)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)

The debug server failed

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! openlayers-workshop@0.0.0 start: `node serve.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openlayers-workshop@0.0.0 start script 'node serve.js'.
npm ERR! This is most likely a problem with the openlayers-workshop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node serve.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openlayers-workshop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls openlayers-workshop
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Temp\openlayers-workshop\npm-debug.log
```
